[package]
name = "ch10-02-traits"
version = "0.1.0"
authors = ["taq-fujihara <taq.fujihara@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
